### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by RobinSchmid7** [LKSeng/rviz_rotatable_image_plugin#3]
I think `catkin build rviz_rotatable_image_display` is wrong but instead `catkin build rviz_rotatable_image_plugin`.
Thanks for the tool!

**Comment by LKSeng** [comment]
Thanks for the heads up (the plugin changed names midway during development). I'll fix it right away!

Glad to hear you managed to find the plugin before I could respond and found the plugin useful!
